### ISSUE TITLE
Build using webpack and imports 

### ISSUE THREAD

**Issue by easyCZ** [vekerdyb/ionic-seed#1]
Using webpack for the build could streamline the process a bit more. Modules could then be required and decoupled from angular/ionic itself. 

A feature module declaration would then define all of its controllers, services etc by giving it a name and requiring the implementation from a different file. 

Let me know your thoughts on this

**Comment by vekerdyb** [comment]
Yeah, agreed. Adding webpack is definitely a goal, will add it to the TODO in readme as well.
